Use GHA for tests and deployment
desklab/doku pull request #54
Opened 2021-04-27 15:09 UTC by ax-sc

2021-04-27 16:22 UTC, jnsdrtlf commented on .github/workflows/unittest.yml
> +        run: pytest doku/tests
I am surprised that this works. Is a database not necessary? Or does this automatically fall back to use SQLite? I don't remember.
If it's not much work, I'd prefer to actually use a real database server and use the production config if possible. This way we can also test the configuration and setup as used in production.

2021-04-27 16:25 UTC, jnsdrtlf commented on .github/workflows/deploy.yml
> +          docker build -t reg.desk-lab.de/doku -t reg.desk-lab.de/doku:${{ github.sha }} .
There is a very simple alternative: [`docker/build-push-action@v2`](https://github.com/marketplace/actions/build-and-push-docker-images). Using this should be much easier.
We would need this for

 1) The python docker image used for the backend server
 2) The apache docker image for the frontend files inside the static directory

2021-04-27 16:26 UTC, jnsdrtlf commented on .github/workflows/deploy.yml
> +          docker login https://reg.desk-lab.de --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD}}
This will also be replaced by [`docker/build-push-action@v2`](https://github.com/marketplace/actions/build-and-push-docker-images)

2021-04-27 16:27 UTC, jnsdrtlf commented on .github/workflows/deploy.yml
> +name: deploy
Deploy is a little bit misleading. We only upload the docker image. Deploying would involve telling the server to pull the new docker image and restart the container. I would suggest doing so using Ansible. I can create a playbook for this soon.

2021-04-27 16:28 UTC, jnsdrtlf commented
Already looks quite promising 👍🏽

2021-04-30 10:25 UTC, jnsdrtlf requested changes

2021-04-30 10:25 UTC, jnsdrtlf commented on .github/workflows/upload.yml
> +      - name: Deploy # TODO: Use docker-action?
With the action `docker/login-action@v1` you have already logged in to the registry, and with the action `docker/build-push-action@v2`, you have already built and **pushed** the container to our registry. Thus, this last step is not necessary.

2021-04-30 10:25 UTC, jnsdrtlf commented on .github/workflows/upload.yml
These two steps (*Install Python Requirements* and *Test*) can be deleted, or am I mistaken? We already have an entire action dedicated to testing our code.

2021-04-30 10:51 UTC, jnsdrtlf commented
@ax-sc could you quickly review the changes I made? I think you can't start a review process as you are the author but it should be enough if you quickly check the `upload.yml` file 😄

2021-04-30 10:52 UTC, jnsdrtlf approved these changes

2021-04-30 11:12 UTC, ax-sc commented
@jnsdrtlf Thanks for the review and the improvements, i think we can merge this now. 

Just for the record, weasyprint should not be necessary for the moment as none of our tests calls it but it´s for sure better to include it from now on (and possibly add also some more tests). However i think we would then still need to install the non-python dependencies of it? At least Cairo has been removed in the latest beta but i think it will take some time until we are able to use the new version.

2021-04-30 11:17 UTC, jnsdrtlf commented
Yes, a WeasyPrint test case is definitely necessary, I'll quickly write one.
WeasyPrint is installed using `apt`, not `pip`, and thus already installs all necessary (non-python-)dependencies. You can take a look at it here: https://packages.ubuntu.com/focal/weasyprint

2021-04-30 11:23 UTC, ax-sc commented
Okay, perfect, i must have missed that you use `apt` while reviewing your changes on a mobile device. The best way to go forward would probably be that you just merge this PR once you have the additional test(s) ready.

2021-04-30 14:24 UTC, merged